language: python

env:
- DJANGO_VERSION=1.7.1 PYTHONPATH=$HOME/build/bericht

python:
  - "3.4"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r requirements.txt

before_script:
  - pwd
  - cp ./deploy/files/travis_settings.py ./local_settings.py
  - mkdir -p ~/bericht-data/media
  - mkdir -p ~/bericht-data/static

script:
  - python manage.py test aggregator
  - python manage.py test aggregator --testrunner=bericht.utils.test_runner.AcceptanceTestSuiteRunner