language: python
env:
- DJANGO_VERSION=1.6.2 PYTHONPATH=$HOME/build/bericht
python:
  - "2.7"
install:
  - pip install -r requirements/project.txt
  - pip install git+git://github.com/dgreisen-cfpb/django-behave.git@my_fixes#django-behave 

before_script:
  - pwd
  - cp ./deploy/travis_settings.py ./local_settings.py
  - mkdir -p ~/bericht-data/media
  - mkdir -p ~/bericht-data/static

script:
  - python manage.py test aggregator
  - python manage.py test aggregator --testrunner=utils.test_runner.AcceptanceTestSuiteRunner

addons:
  sauce_connect:
    username: "bericht"
    secure: "doVdgRnppN/mofGU/+HWMr18ZDaCTf8TRSjjtjO4+VPLdNGp79lEOvx3U2DT6xjWDhB1Q3eIpgNei7LniW/PCIM5I0iTUKMDEKUBwD91pu7iMukGWKkaCa9/Ewh2YkYt1JBbXclRDN/4pQRmcgeOwsULfGu5ev+Q0RtkUnK7EPA="
